---
- name: Install
  hosts: locals
  connection: local
  tasks:
  - name: Debug
    debug:
      msg: "Hello"
  - name: Install ruby 2.6 by yum
    shell: | 
      dnf -y module reset ruby
      dnf -y module enable ruby:2.6

  - name: Install virt group
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - "@virt" 
    - virt-install
    - ruby
    - ruby-devel
    - make 
    - gcc
    - rpm-build 
    - ruby-devel 
    - zlib-devel
  - name: Install latest available version of nokogiri
    gem:
      name: nokogiri
      state: latest
      user_install: yes
