---
- name: Install
  hosts: locals
  connection: local
  tasks:
  - name: Debug
    debug:
      msg: "Hello"
  - name: Install ntpdate
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - "@virt" 
    - virt-install
