---
- name: Install
  hosts: locals
  connection: local
  tasks:
  - name: Debug
    debug:
      msg: "Hello"
  - name: Install ruby 2.6 by yum
    shell: | 
      dnf -y module reset ruby
      dnf -y module enable ruby:2.6
    args:
      warn: false

  - name: Install virt group
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - "@virt" 
    - virt-install
    - ruby
    - ruby-devel
    - make 
    - gcc
    - rpm-build 
    - ruby-devel 
    - zlib-devel
  - name: Install latest available version of nokogiri
    gem:
      name: nokogiri
      state: latest
      user_install: no
  - name: Add Hashicorp repo
    get_url:
      url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      dest: /etc/yum.repos.d/hashicorp.repo
  - name: Install vagrant
    dnf:
      name: vagrant
      state: present
